<?php
namespace App\Services;
use App\Models\Documento;
use App\Models\TipoDocumento;
use Illuminate\Support\Facades\DB;
class DocumentService {
 public function __construct(private DocumentNumberService $numeracion, private InventoryService $inventario) {}
 public function crear(array $datos, array $detalles): Documento { return DB::transaction(function() use($datos,$detalles){$tipo=TipoDocumento::where('codigo',$datos['tipo_codigo'])->where('activo',true)->firstOrFail();$numero=$this->numeracion->siguiente($tipo,$datos['prefijo']??null);unset($datos['tipo_codigo']);$doc=Documento::create(array_merge($datos,['tipo_documento_id'=>$tipo->id,'prefijo'=>$numero['prefijo'],'numero'=>$numero['numero'],'consecutivo'=>$numero['consecutivo'],'estado'=>'borrador']));foreach($detalles as $linea)$doc->detalles()->create($linea);return $doc;}); }
 public function registrar(Documento $documento, int $usuarioId): Documento { return DB::transaction(function() use($documento,$usuarioId){$documento->refresh()->load('tipo','detalles');if($documento->estado!=='borrador')throw new \DomainException('Solo se registran documentos en borrador.');foreach($documento->detalles as $detalle){if(!$detalle->producto_id||!$detalle->tipo_movimiento_inventario)continue;$bodega=$detalle->tipo_movimiento_inventario==='SALIDA'?$detalle->bodega_origen_id:$detalle->bodega_destino_id;if(!$bodega)throw new \DomainException('Falta la bodega del movimiento de inventario.');$this->inventario->mover($documento,$detalle->producto_id,$bodega,$detalle->tipo_movimiento_inventario,(float)$detalle->cantidad,$detalle->id);} $documento->update(['estado'=>'registrado','registrado_at'=>now(),'registrado_por'=>$usuarioId]);return $documento->fresh();}); }
 public function anular(Documento $documento,int $usuarioId): Documento { return DB::transaction(function() use($documento,$usuarioId){$documento->refresh()->load('movimientosInventario');if($documento->estado!=='registrado')throw new \DomainException('Solo se anulan documentos registrados.');foreach($documento->movimientosInventario as $mov){$tipo=$mov->tipo==='ENTRADA'?'SALIDA':'ENTRADA';$this->inventario->mover($documento,$mov->producto_id,$mov->bodega_id,$tipo,(float)$mov->cantidad,$mov->documento_detalle_id);} $documento->update(['estado'=>'anulado','anulado_at'=>now(),'anulado_por'=>$usuarioId]);return $documento->fresh();}); }
}
