<?php
namespace App\Http\Controllers;
use App\Models\Compra; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class CompraController extends Controller {
 public function index(){return view('compras.index');}
 public function data(){return response()->json(['data'=>Compra::with(['proveedor','usuario:id,name'])->latest()->get()]);}
 public function siguienteConsecutivo(Request $r){$prefijo=strtoupper(trim((string)$r->string('prefijo','FC')));return response()->json(['consecutivo'=>(Compra::where('prefijo',$prefijo)->max('consecutivo')??0)+1]);}
 public function store(Request $r){$d=$r->validate(['prefijo'=>'required|max:10','consecutivo'=>'required|integer|min:1','numero_factura'=>'required|max:50','proveedor_id'=>'required|exists:terceros,id','fecha'=>'required|date','observaciones'=>'nullable','items'=>'required|array|min:1','items.*.producto_id'=>'required|exists:productos,id','items.*.bodega_id'=>'required|exists:bodegas,id','items.*.cantidad'=>'required|numeric|gt:0','items.*.costo_unitario'=>'required|numeric|min:0','pagos'=>'nullable|array','confirmar'=>'boolean']); return DB::transaction(function()use($d,$r){$c=Compra::create(['prefijo'=>strtoupper($d['prefijo']),'consecutivo'=>$d['consecutivo'],'numero_factura'=>$d['numero_factura'],'proveedor_id'=>$d['proveedor_id'],'user_id'=>$r->user()->id,'fecha'=>$d['fecha'],'observaciones'=>$d['observaciones']??null,'estado'=>!empty($d['confirmar'])?'confirmada':'borrador','registrado_at'=>!empty($d['confirmar'])?now():null]);$tot=['subtotal'=>0,'descuentos'=>0,'iva'=>0,'ico'=>0,'retenciones'=>0,'otros_cargos'=>0,'total'=>0];foreach($d['items'] as $i){$base=$i['cantidad']*$i['costo_unitario'];$desc=$base*(($i['descuento_porcentaje']??0)/100);$grav=$base-$desc;$iva=$grav*(($i['iva_porcentaje']??0)/100);$ico=$grav*(($i['ico_porcentaje']??0)/100);$ret=($i['retefuente']??0)+($i['reteiva']??0)+($i['reteica']??0);$otros=$i['otros_cargos']??0;$total=$grav+$iva+$ico+$otros-$ret;$c->detalles()->create(array_merge($i,['subtotal'=>$grav,'total'=>$total]));foreach(['subtotal'=>$base,'descuentos'=>$desc,'iva'=>$iva,'ico'=>$ico,'retenciones'=>$ret,'otros_cargos'=>$otros,'total'=>$total] as $k=>$v)$tot[$k]+=$v;if($c->estado==='confirmada')DB::table('inventarios')->updateOrInsert(['producto_id'=>$i['producto_id'],'bodega_id'=>$i['bodega_id']],['stock'=>DB::raw('COALESCE(stock,0) + '.$i['cantidad']),'updated_at'=>now(),'created_at'=>now()]);} $c->update($tot);foreach($d['pagos']??[] as $p)if(($p['valor']??0)>0)$c->pagos()->create($p);return response()->json(['success'=>true,'data'=>$c->load('detalles','pagos')]);});}
 public function show(Compra $compra){return response()->json($compra->load('proveedor','detalles.producto','detalles.bodega','pagos'));}
 public function update(Request $r, Compra $compra){
  if($compra->estado!=='borrador')return response()->json(['message'=>'Solo se pueden editar compras en borrador'],422);
  $d=$r->validate(['prefijo'=>'required|max:10','consecutivo'=>'required|integer|min:1','numero_factura'=>'required|max:50','proveedor_id'=>'required|exists:terceros,id','fecha'=>'required|date','observaciones'=>'nullable','items'=>'required|array|min:1','items.*.producto_id'=>'required|exists:productos,id','items.*.bodega_id'=>'required|exists:bodegas,id','items.*.cantidad'=>'required|numeric|gt:0','items.*.costo_unitario'=>'required|numeric|min:0','confirmar'=>'boolean']);
  return DB::transaction(function()use($d,$compra){
   $compra->detalles()->delete();$tot=['subtotal'=>0,'descuentos'=>0,'iva'=>0,'ico'=>0,'retenciones'=>0,'otros_cargos'=>0,'total'=>0];
   foreach($d['items'] as $i){$base=$i['cantidad']*$i['costo_unitario'];$desc=$base*(($i['descuento_porcentaje']??0)/100);$grav=$base-$desc;$iva=$grav*(($i['iva_porcentaje']??0)/100);$ico=$grav*(($i['ico_porcentaje']??0)/100);$ret=($i['retefuente']??0)+($i['reteiva']??0)+($i['reteica']??0);$otros=$i['otros_cargos']??0;$total=$grav+$iva+$ico+$otros-$ret;$compra->detalles()->create(array_merge($i,['subtotal'=>$grav,'total'=>$total]));foreach(['subtotal'=>$base,'descuentos'=>$desc,'iva'=>$iva,'ico'=>$ico,'retenciones'=>$ret,'otros_cargos'=>$otros,'total'=>$total] as $k=>$v)$tot[$k]+=$v;}
   $compra->update(array_merge(['prefijo'=>strtoupper($d['prefijo']),'consecutivo'=>$d['consecutivo'],'numero_factura'=>$d['numero_factura'],'proveedor_id'=>$d['proveedor_id'],'fecha'=>$d['fecha'],'observaciones'=>$d['observaciones']??null],$tot));
   if(!empty($d['confirmar'])){foreach($compra->detalles as $detalle)DB::table('inventarios')->updateOrInsert(['producto_id'=>$detalle->producto_id,'bodega_id'=>$detalle->bodega_id],['stock'=>DB::raw('COALESCE(stock,0) + '.$detalle->cantidad),'updated_at'=>now(),'created_at'=>now()]);$compra->update(['estado'=>'confirmada','registrado_at'=>now()]);}
   return response()->json(['success'=>true,'data'=>$compra->fresh()->load('detalles','pagos')]);
  });
 }
 public function registrar(Compra $compra){if($compra->estado!=='borrador')return response()->json(['message'=>'La compra ya fue registrada'],422);return DB::transaction(function()use($compra){foreach($compra->detalles as $d)DB::table('inventarios')->updateOrInsert(['producto_id'=>$d->producto_id,'bodega_id'=>$d->bodega_id],['stock'=>DB::raw('COALESCE(stock,0) + '.$d->cantidad),'updated_at'=>now(),'created_at'=>now()]);$compra->update(['estado'=>'confirmada','registrado_at'=>now()]);return response()->json(['success'=>true]);});}
 public function revertirRegistro(Compra $compra){if($compra->estado!=='confirmada')return response()->json(['message'=>'Solo se puede revertir una compra confirmada'],422);return DB::transaction(function()use($compra){foreach($compra->detalles as $d){$stock=DB::table('inventarios')->where(['producto_id'=>$d->producto_id,'bodega_id'=>$d->bodega_id])->lockForUpdate()->value('stock');if($stock===null||$stock<$d->cantidad)return response()->json(['message'=>'No se puede revertir: el inventario ya no tiene existencias suficientes para '.$d->producto_id],422);}foreach($compra->detalles as $d)DB::table('inventarios')->where(['producto_id'=>$d->producto_id,'bodega_id'=>$d->bodega_id])->decrement('stock',$d->cantidad);$compra->update(['estado'=>'borrador','registrado_at'=>null]);return response()->json(['success'=>true]);});}
 public function anular(Compra $compra){if($compra->estado!=='confirmada')return response()->json(['message'=>'Solo se anulan compras confirmadas'],422);return DB::transaction(function()use($compra){foreach($compra->detalles as $d){$stock=DB::table('inventarios')->where(['producto_id'=>$d->producto_id,'bodega_id'=>$d->bodega_id])->lockForUpdate()->value('stock');if($stock===null||$stock<$d->cantidad)return response()->json(['message'=>'No se puede anular: el inventario ya no tiene existencias suficientes para '.$d->producto_id],422);}foreach($compra->detalles as $d)DB::table('inventarios')->where(['producto_id'=>$d->producto_id,'bodega_id'=>$d->bodega_id])->decrement('stock',$d->cantidad);$compra->update(['estado'=>'anulada']);return response()->json(['success'=>true]);});}
 public function revertir(Compra $compra){if($compra->estado!=='anulada')return response()->json(['message'=>'Solo se revierten compras anuladas'],422);return DB::transaction(function()use($compra){foreach($compra->detalles as $d)DB::table('inventarios')->updateOrInsert(['producto_id'=>$d->producto_id,'bodega_id'=>$d->bodega_id],['stock'=>DB::raw('COALESCE(stock,0) + '.$d->cantidad),'updated_at'=>now(),'created_at'=>now()]);$compra->update(['estado'=>'confirmada','registrado_at'=>now()]);return response()->json(['success'=>true]);});}
}
